# -----------------
# Global variables
# -----------------
# Name of the project
name: Dr Paul Richmond

# Subtitle - shown in the header of the website
subtitle: Research Software Engineer

# Meta description (<=160 characters) - used by search engines
description: Dr Paul Richmond (Research Software Engineer) personal website - University of Sheffield
keywords: Paul Richmond, Paul, Richmond, P.Richmond, Research Software Engineer, Research Fellow, Department of Computer Science, Agent Based Modelling, Agent Based Simulation, Computational Neuroscience, FLAME GPU, FLAME, GPU, GPGPU, CUDA, Graphics Processing Unit


# -----------------
# Jekyll settings
# -----------------

# Exclude files or directories from being hosted on the web
exclude: ['package.json', 'readme.md']

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Timezone for date/time used on the website
timezone: Europe/London

# Local development configuration settings
source: .
destination: ./_site
host: 0.0.0.0
port: 4000
baseurl: 
url: http://localhost:4000
lsi: false

# Markdown processing settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
